set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g prefix C-a
set-option -g default-shell /bin/zsh

set -g terminal-overrides ',xterm-256color:Tc'
set -g default-terminal "screen-256color"
set -as terminal-overrides ',xterm*:sitm=\E[3m'
set -g @continuum-restore 'on'
bind r source-file ~/.tmux.conf

# Use Alt-arrow keys to switch panes
bind -n S-Left select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up select-pane -U
bind -n S-Down select-pane -D

# Use C-a to switch resize panes
bind-key M-Left resize-pane -L 5
bind-key M-Right resize-pane -D 5
bind-key M-Up resize-pane -U 5
bind-key M-Down resize-pane -R 5
